# U2 Lesson 7 - Applying

## Data Science, Fall 2025

Objective:
By the end of this lesson, you will understand how functions and the apply method support data cleaning, transformation, and filtering in the datascience library, and how these tools connect to boolean logic and .where(). You will:
* Differentiate between writing a function with parameters and applying that function to a dataset
* Apply custom functions to columns in order to transform or clean data
* Interpret the role of boolean arrays in filtering and explain how they connect to .where()
* Connect the behavior of apply with the logic behind .where() to strengthen your mental model of filtering

In [1]:
from datascience import *
import numpy as np

In [ ]:
temps = Table().with_column("Temperature", make_array(50, 72, 90, 4, 100, 38, 90, 70, 68))

def hot_or_cold(t):
    if t > 75:
        return "Hot"
    else:
        return "Cold"

temps = temps.with_column("Label", temps.apply(hot_or_cold, "Temperature"))
temps.show()

## Motivation

Until now, we've primarily worked with just the data we've been given in our tables. However, oftentimes some of our data needs to be manipulated or "cleaned" before we can work with it to infer things about the world.

For example, we have been given this table of dogs and their ages in 'human years'. While this may be useful in some contexts, what if we want to know each dog's age in 'dog years'. For this example, we will use the (incorrect) conversion of one human year being equivalent to 7 dogs years — you can read about a more accurate conversion [here](https://pets.webmd.com/dogs/how-to-calculate-your-dogs-age).

We already know how to convert the column `age` to dog years using **array arithmetic**. We can then add this new array as a new column in our table.

In [ ]:
pups = Table.read_table('data/pups.csv')
pups.show(3)

## Apply

Now that we know how to write our own functions, we can leverage these functions to manipulate our tables in particular ways. This is really useful if we want to extract or convert data in our table to generate new insights about it.

We can use `tbl.apply(col, func)` to **apply** the function `func` to the column `col`. This creates an array when each item is the result of evaluating `func` with the corresponding item in `col` as the input. This essentially allows you to do multiple function calls all at the same time.

In [4]:
def seven_times(x):
    return 7 * x

In [ ]:
... # Apply the `seven_times` function to the column `age` in the `pups` table

Note, we wouldn't actually use the above example with `.apply` since we could just write `pups.column('age') * 7`.

Here's a more useful example:

In [6]:
def email_from_name(name):
    first, last = name.split(' ')
    email = first + '.' + last + '@dogschool.edu'
    return email.lower()

In [7]:
# Can use email_from_name on a single argument
email_from_name('Champ Major')

'champ.major@dogschool.edu'

In [13]:
emails = pups.apply(email_from_name, 'name')

In [14]:
pups.with_column("Email Address", emails)

name         | age  | size   | Email Address
Junior Smith | 11   | medium | junior.smith@dogschool.edu
Rex Rogers   | 7    | big    | rex.rogers@dogschool.edu
Flash Heat   | 3    | big    | flash.heat@dogschool.edu
Reese Bo     | 4    | medium | reese.bo@dogschool.edu
Polo Cash    | 2    | small  | polo.cash@dogschool.edu

In [ ]:
# Write an age converter for dogs --> human that multiplies by 6 if the dog is small, 7 if the dog is medium, and 8 if the dog is big.

In [ ]:
# Add the newly computed age to a column titled "accurage human years"

Notice how fast and easy that was!

### Quick Check 1

In [19]:
countries = Table.read_table("data/countries.csv")

# Create a function to take a population string and transform it into an integer (We did this last week!)

# Use apply with your function to generate the new value

# Update the table with the new population integers




# Display the country data
countries.sort('Population', descending = True)

Rank | Country(or dependent territory) | Population | % of world | Date        | Source(official or UN)
183  | Seychelles                      | 98,462     | 0.00126%   | 30 Jun 2020 | National semi-annual estimate[185]
156  | Djibouti                        | 976,107    | 0.0125%    | 1 Jul 2019  | National annual projection[152]
184  | Antigua and Barbuda             | 97,895     | 0.00125%   | 1 Jul 2020  | National annual projection[186]
15   | Vietnam                         | 96,483,981 | 1.23%      | 1 Jul 2019  | National annual estimate[15]
16   | DR Congo                        | 90,935,800 | 1.16%      | 1 Jul 2020  | National annual projection[16]
–    | Saint Barthélemy (France)       | 9,961      | 0.000127%  | 1 Jan 2017  | National annual estimate[205]
91   | Hungary                         | 9,769,526  | 0.125%     | 1 Jan 2020  | National annual estimate[88]
92   | Belarus                         | 9,408,400  | 0.120%     | 1 Jan 2020  | National annual estimate[89]
93   | United Arab Emirates            | 9,366,829  | 0.120%     | 1 Jul 2018  | National annual estimate[90]
94   | Tajikistan                      | 9,313,800  | 0.119%     | 1 Jan 2020  | National annual estimate[91]
... (232 rows omitted)

## Masking

Python also allows us to select elements of an array or rows in a table based off of **boolean masking** (also called boolean indexing).

In [ ]:
numbers = np.array([15, 14, -2, 1, 9])

The syntax for boolean masking is not what we're used to, so don't worry too much about understanding it.

In [ ]:
... # Use boolean masking to get only the first and third elements of `numbers`

Notice how masking the `numbers` array with an array of booleans allowed us to get only the elements of `numbers` that we wanted.

Let's see another example:

In [10]:
gradebook = Table().with_columns(
    'Name', np.array(['Carrera', 'Panamera', 'Taycan', 'Cayenne', 'Macan', 'Cayman', 'Boxster']),
    'Grading Option', np.array(['GRD', 'PNP', 'PNP', 'GRD', 'GRD', 'GRD', 'PNP']),
    'Score', np.array([98, 86, 67.5, 45, 82, 88, 71])
)

In [8]:
gradebook

Name     | Grading Option | Score
Carrera  | GRD            | 98
Panamera | PNP            | 86
Taycan   | PNP            | 67.5
Cayenne  | GRD            | 45
Macan    | GRD            | 82
Cayman   | GRD            | 88
Boxster  | PNP            | 71

`gradebook` is a table of fake students, their scores/grades, and their grading option (letter graded - "GRD" or Pass/No Pass - "PNP"). Let's use boolean masking to get only the students whose grading option is "GRD".

In [ ]:
... # Use boolean indexing and `.where` to get only the students whose grading option is "GRD"

This weird `.where` call is actually what's happening under the hood when we do `gradebook.where("Grading Option", "GRD")`

In [ ]:
gradebook.where("Grading Option", "GRD")

In [ ]:
# You'll learn what this line means next lecture
letter_grade = gradebook.column("Grading Option") == 'GRD'

In [ ]:
gradebook.where(letter_grade)

That being said, boolean masking is pretty tedious, so we almost exclusively rely on the usual `.where` syntax.

### Example: Countries

Run the following cell – ignore the `lambda` parts:

In [ ]:
# This is the countries table again, but I'm cleaning up the "Country" column.

countries = Table.read_table('data/countries.csv')
countries = countries.relabeled('Country(or dependent territory)', 'Country') \
           .relabeled('% of world', '%') \
           .relabeled('Source(official or UN)', 'Source')
countries = countries.with_columns(
    'Country', countries.apply(lambda s: s[:s.index('[')].lower() if '[' in s else s.lower(), 'Country'),
    'Population', countries.apply(lambda i: int(i.replace(',', '')), 'Population'),
    '%', countries.apply(lambda f: float(f.replace('%', '')), '%')
)

In [12]:
countries

Rank | Country       | Population | %    | Date        | Source
1    | china         | 1405936040 | 17.9 | 27 Dec 2020 | National population clock[3]
2    | india         | 1371366679 | 17.5 | 27 Dec 2020 | National population clock[4]
3    | united states | 330888778  | 4.22 | 27 Dec 2020 | National population clock[5]
4    | indonesia     | 269603400  | 3.44 | 1 Jul 2020  | National annual projection[6]
5    | pakistan      | 220892331  | 2.82 | 1 Jul 2020  | UN Projection[2]
6    | brazil        | 212523810  | 2.71 | 27 Dec 2020 | National population clock[7]
7    | nigeria       | 206139587  | 2.63 | 1 Jul 2020  | UN Projection[2]
8    | bangladesh    | 169885314  | 2.17 | 27 Dec 2020 | National population clock[8]
9    | russia        | 146748590  | 1.87 | 1 Jan 2020  | National annual estimate[9]
10   | mexico        | 127792286  | 1.63 | 1 Jul 2020  | National annual projection[10]
... (232 rows omitted)

Let's find all of the countries whose name starts or ends with the letter 'a':

In [ ]:
# Create a function to return true if the first or last letter of the country name is "a"

In [ ]:
# Apply this function to the table

In [ ]:
# Use where in conjunction with your applied return array to show only the desired countries